import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import { appMenuTemplate, RENDERER_OWNED_ACCELERATORS } from "../src/main/menu-template.ts";
import { trayIcon, trayImageFor, windowChrome } from "../src/main/platform-shell.ts";

/**
 * The desktop shell's per-platform choices: the tray image, the window chrome and the
 * application menu. macOS is pinned as it was, and win32 is pinned where the macOS answer
 * does not work there (M2.9 in `docs/plans/windows-support/plan.md`).
 */

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const BUILD_DIR = join(REPO_ROOT, "build");
const APP_NAME = "Mission Control";

type Item = {
  label?: string;
  role?: string;
  type?: string;
  accelerator?: string;
  click?: unknown;
  submenu?: Item[];
};

/** A template's shape without its click closures, which differ on every call. */
type Shape = { label?: string; role?: string; type?: string; accelerator?: string; submenu?: Shape[] };
function shape(items: Item[]): Shape[] {
  return items.map(({ label, role, type, accelerator, submenu }) => ({
    ...(label !== undefined ? { label } : {}),
    ...(role !== undefined ? { role } : {}),
    ...(type !== undefined ? { type } : {}),
    ...(accelerator !== undefined ? { accelerator } : {}),
    ...(submenu ? { submenu: shape(submenu) } : {}),
  }));
}

function flatten(items: Item[]): Item[] {
  return items.flatMap((item) => [item, ...flatten(item.submenu ?? [])]);
}

function menu(platform: NodeJS.Platform | undefined, claimed = false): Item[] {
  const handlers = { onOpenSettings: () => {}, onCheckForUpdates: () => {} };
  const state = { rendererOwnsNumberRow: claimed };
  return (platform === undefined
    ? appMenuTemplate(APP_NAME, handlers, state)
    : appMenuTemplate(APP_NAME, handlers, state, platform)) as Item[];
}

test("macOS keeps its template tray image; win32 gets a colored .ico that is not a template", () => {
  assert.deepEqual(trayIcon("darwin", BUILD_DIR), {
    path: join(BUILD_DIR, "trayTemplate.png"),
    template: true,
  });
  assert.deepEqual(trayIcon("linux", BUILD_DIR), trayIcon("darwin", BUILD_DIR));
  // A template image is a black mask the macOS menu bar recolors. Nothing recolors it on the
  // Windows taskbar, which is dark by default, so marking it a template there would draw a
  // black shape on a dark bar.
  assert.deepEqual(trayIcon("win32", BUILD_DIR), {
    path: join(BUILD_DIR, "tray.ico"),
    template: false,
  });
});

test("the win32 tray icon is a well-formed .ico with the sizes the notification area asks for", () => {
  // Generated by `scripts/gen-icons.mjs` and committed, so a dev run on Windows never needs
  // an image toolchain. Read here as bytes, because `nativeImage` exists only in Electron.
  const ico = readFileSync(trayIcon("win32", BUILD_DIR).path);
  assert.equal(ico.readUInt16LE(0), 0, "reserved header field");
  assert.equal(ico.readUInt16LE(2), 1, "type 1 is an icon");
  const count = ico.readUInt16LE(4);
  const sizes: number[] = [];
  for (let i = 0; i < count; i += 1) {
    const entry = 6 + 16 * i;
    const width = ico.readUInt8(entry) || 256;
    assert.equal(ico.readUInt8(entry + 1) || 256, width, "entries are square");
    const length = ico.readUInt32LE(entry + 8);
    const offset = ico.readUInt32LE(entry + 12);
    assert.ok(offset + length <= ico.length, `the ${width}px entry runs past the file`);
    const png = ico.subarray(offset, offset + length);
    assert.deepEqual([...png.subarray(0, 8)], [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
    // The PNG's own IHDR width agrees with the directory entry.
    assert.equal(png.readUInt32BE(16), width, `the ${width}px entry holds a different size`);
    sizes.push(width);
  }
  // 16px at 100% display scale, 24px at 150%, 32px at 200%.
  for (const size of [16, 24, 32]) assert.ok(sizes.includes(size), `no ${size}px entry`);
  // And the macOS template the other branch loads is still there.
  assert.ok(readFileSync(trayIcon("darwin", BUILD_DIR).path).length > 0);
});

/** A stand-in for `nativeImage` that records whether it was marked a template. */
class FakeImage {
  template: boolean | null = null;
  constructor(readonly path: string, private readonly empty = false) {}
  isEmpty(): boolean {
    return this.empty;
  }
  setTemplateImage(option: boolean): void {
    this.template = option;
  }
}

test("the tray marks the macOS image a template and leaves the win32 image colored", () => {
  // This is where the platform's answer takes effect: `tray.ts` hands `nativeImage` to it.
  const load = (path: string) => new FakeImage(path);
  const fallback = new FakeImage("(empty)", true);

  const darwin = trayImageFor(trayIcon("darwin", BUILD_DIR), load, () => fallback);
  assert.equal(darwin.path, join(BUILD_DIR, "trayTemplate.png"));
  assert.equal(darwin.template, true);

  const win32 = trayImageFor(trayIcon("win32", BUILD_DIR), load, () => fallback);
  assert.equal(win32.path, join(BUILD_DIR, "tray.ico"));
  assert.equal(win32.template, null, "the win32 tray icon was marked a template");

  // A missing or unreadable file falls back to the empty image, untouched.
  assert.equal(trayImageFor(trayIcon("darwin", BUILD_DIR), () => null, () => fallback), fallback);
  const unreadable = trayImageFor(
    trayIcon("darwin", BUILD_DIR),
    (path) => new FakeImage(path, true),
    () => fallback,
  );
  assert.equal(unreadable, fallback);
  assert.equal(fallback.template, null);
});

test("the shell takes its tray image and window chrome from the running platform", () => {
  // The two answers above are pure; these are the three lines that hand them to Electron.
  // Same shape as the `menu.ts` pin in `app-menu-template.test.ts`: none of these files can
  // be imported outside the Electron process.
  const source = (path: string): string => readFileSync(join(REPO_ROOT, path), "utf8");
  assert.match(
    source("src/main/index.ts"),
    /trayIcon: trayIcon\(process\.platform, join\(appRoot, "build"\)\)/,
    "index.ts no longer picks the tray icon for the running platform",
  );
  const tray = source("src/main/tray.ts");
  assert.match(tray, /return trayImageFor\(\s*icon,/, "tray.ts no longer loads its image through trayImageFor");
  assert.doesNotMatch(tray, /setTemplateImage/, "tray.ts decides the template itself again");
  assert.match(
    source("src/main/window.ts"),
    /\.\.\.windowChrome\(process\.platform\)/,
    "window.ts no longer takes its chrome from the running platform",
  );
});

test("macOS keeps its inset traffic lights; win32 keeps its native frame and window controls", () => {
  assert.deepEqual(windowChrome("darwin"), {
    titleBarStyle: "hidden",
    trafficLightPosition: { x: 20, y: 28 },
  });
  assert.deepEqual(windowChrome("linux"), windowChrome("darwin"));
  // `titleBarStyle: "hidden"` on win32 takes the minimize, maximize and close buttons away
  // with the title bar, so it must not be asked for there.
  const win32 = windowChrome("win32");
  assert.equal("titleBarStyle" in win32, false);
  assert.equal("trafficLightPosition" in win32, false);
  assert.equal(win32.autoHideMenuBar, true);
});

test("the macOS application menu is unchanged, and is the default", () => {
  const darwin = menu("darwin");
  assert.deepEqual(
    darwin.map((item) => item.label ?? item.role),
    [APP_NAME, "editMenu", "View", "windowMenu"],
  );
  assert.deepEqual(
    (darwin[0]?.submenu ?? []).map((item) => item.label ?? item.role ?? item.type),
    [
      "about", "Check for Updates…", "separator", "Settings…", "separator", "services",
      "separator", "hide", "hideOthers", "unhide", "separator", "quit",
    ],
  );
  // `menu.ts` passes `process.platform`; every caller that does not still gets this menu.
  for (const claimed of [false, true]) {
    assert.deepEqual(shape(menu(undefined, claimed)), shape(menu("darwin", claimed)));
    assert.deepEqual(shape(menu("linux", claimed)), shape(menu("darwin", claimed)));
  }
});

test("the win32 menu has no macOS app menu, and keeps every command it carried", () => {
  const win32 = menu("win32");
  assert.deepEqual(
    win32.map((item) => item.label ?? item.role),
    ["File", "editMenu", "View", "windowMenu", "Help"],
  );
  assert.equal(win32.some((item) => item.label === APP_NAME), false, "a macOS app menu on win32");
  const roles = flatten(win32).map((item) => item.role);
  for (const role of ["about", "services", "hide", "hideOthers", "unhide"]) {
    assert.equal(roles.includes(role), false, `the macOS-only "${role}" role is on win32`);
  }

  const file = win32.find((item) => item.label === "File")?.submenu ?? [];
  const settings = file.find((item) => item.label === "Settings…");
  assert.equal(settings?.accelerator, "CmdOrCtrl+,");
  assert.equal(typeof settings?.click, "function");
  // Electron labels the quit role "Exit" on win32.
  assert.equal(file.at(-1)?.role, "quit");

  const help = win32.find((item) => item.label === "Help")?.submenu ?? [];
  const updates = help.find((item) => item.label === "Check for Updates…");
  assert.equal(typeof updates?.click, "function");
});

test("the win32 View menu is the macOS one, so the number-row handover holds there too", () => {
  for (const claimed of [false, true]) {
    const view = (platform: NodeJS.Platform) =>
      shape(menu(platform, claimed).filter((item) => item.label === "View"));
    assert.deepEqual(view("win32"), view("darwin"));
  }
  const claimedChords = new Set(
    flatten(menu("win32", true))
      .map((item) => item.accelerator?.toLowerCase())
      .filter(Boolean),
  );
  for (const accelerator of RENDERER_OWNED_ACCELERATORS) {
    assert.equal(claimedChords.has(accelerator.toLowerCase()), false, `win32 menu claims ${accelerator}`);
  }
});

test("dev:electron sets no environment inline in a concurrently command", () => {
  // concurrently runs each command through cmd.exe on win32, whatever npm's script-shell is,
  // and cmd.exe has no `VAR=value command` form. The variable is set inside an npm script
  // instead, which npm runs through its script-shell: Git Bash on Windows (D30).
  const pkg = JSON.parse(readFileSync(join(REPO_ROOT, "package.json"), "utf8")) as {
    scripts: Record<string, string>;
  };
  for (const name of ["dev", "dev:electron", "dev:desktop", "dev:start"]) {
    const script = pkg.scripts[name] ?? "";
    assert.match(script, /concurrently/, `${name} no longer runs concurrently`);
    const commands = [...script.matchAll(/"([^"]+)"/g)].map((match) => match[1] ?? "");
    for (const command of commands) {
      assert.doesNotMatch(command, /^\s*[A-Za-z_][A-Za-z0-9_]*=/, `${name} runs "${command}"`);
    }
  }
  assert.match(pkg.scripts["dev:electron"] ?? "", /"npm run dev:electron:app"/);
  assert.equal(
    pkg.scripts["dev:electron:app"],
    "MISSION_DEV_SERVER_URL=http://localhost:5173 electronmon .",
  );
});
