import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { after, describe, test } from "node:test";
import {
  FLAKY_TESTS_CHECK_NAME,
  flakeIssueMarker,
  flakeKey,
  flakeOccurrenceMarker,
  parseFlakeSummary,
  type FlakeReport,
  type FlakeReportTest,
} from "../src/shared/flake-report.ts";
import { runContextFrom, type RunContext } from "../src/flake-report-action/context.ts";
import { gitHubClient, type FetchLike } from "../src/flake-report-action/github.ts";
import { publish } from "../src/flake-report-action/publish.ts";
import { classifyPlaywright, rerunJUnit, type SpawnCommand } from "../src/flake-report-action/rerun.ts";

// What is at stake: CI's verdict. A flake must keep its job green and reach its history issue;
// a real failure, or a job that failed for a reason no test explains, must never be classified
// away. The committed action is also generated, so the first test holds it to its generator.

const root = resolve(import.meta.dirname, "..");
const actionDir = join(root, ".github", "actions", "mission-flake-report");
const skillAssetDir = join(root, "skills", "testing-setup", "assets", "mission-flake-report");
const scratch = mkdtempSync(join(tmpdir(), "mission-flake-action-"));
after(() => rmSync(scratch, { recursive: true, force: true }));

test("both committed copies of the action are exactly what the generator produces", async () => {
  const { renderFlakeReportAction, FLAKE_REPORT_ACTION_DIRS } = await import("../scripts/build-flake-report-action.ts");
  const files = await renderFlakeReportAction();
  assert.deepEqual(Object.keys(files).sort(), ["action.yml", "index.mjs"]);
  // CI's copy, and the one the testing-setup skill installs into other repositories.
  assert.deepEqual(FLAKE_REPORT_ACTION_DIRS, [actionDir, skillAssetDir]);
  for (const dir of FLAKE_REPORT_ACTION_DIRS) {
    for (const [name, text] of Object.entries(files)) {
      assert.equal(
        readFileSync(join(dir, name), "utf8"),
        text,
        `${join(dir, name)} is stale: run \`npm run build:flake-report-action\` and commit the result`,
      );
    }
  }
  assert.match(files["index.mjs"]!, /^\/\/ mission-flake-report \d+\.\d+\.\d+\n\/\/ Generated by scripts\/build-flake-report-action\.ts/);
  assert.match(files["action.yml"]!, /using: node24/);
});

test("CI's first run and its rerun share one test invocation", () => {
  // `npm test` and the unit shard's rerun-command both go through `test:run`, the one owner of
  // how this repository gets JUnit out of `node --test`, so the classifier compares like with like.
  const scripts = (JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as { scripts: Record<string, string> }).scripts;
  assert.match(scripts.test!, /^npm run --silent test:run -- /);
  assert.match(scripts["test:run"]!, /\$\{MISSION_TEST_JUNIT:\+--test-reporter=spec .*--test-reporter=junit --test-reporter-destination=\$MISSION_TEST_JUNIT\}/);
  const shard = readFileSync(join(root, ".github", "actions", "run-unit-shard", "action.yml"), "utf8");
  const rerun = /^\s+rerun-command:\s*(.+)$/m.exec(shard)?.[1];
  assert.equal(rerun, "xvfb-run -a env MISSION_TEST_JUNIT={junit} npm run --silent test:run -- {files}");

  // The shard calls `test:run` itself, after provisioning once through `pretest`, so `posttest`
  // never reruns `test:workflow-evidence` files the shard's glob already holds.
  const steps = shard.split("\n").filter((line) => !/^\s*#/.test(line)).join("\n");
  assert.equal(steps.match(/npm run pretest/g)?.length, 1);
  assert.doesNotMatch(steps, /\bnpm test\b|install-electron|build:state-lock-native/);
  assert.match(steps, /^\s+xvfb-run -a npm run --silent test:run -- .*--test-shard="\$MISSION_TEST_SHARD" 'test\/\*\*\/\*\.test\.ts'$/m);
});

// JUnit fixtures, in the shape `node --test --test-reporter=junit` writes.
function junit(cases: { name: string; file: string; failed?: boolean; classname?: string }[]): string {
  const body = cases.map((c) => {
    const attrs = `name="${c.name}" classname="${c.classname ?? "test"}" file="${c.file}"`;
    return c.failed
      ? `<testcase ${attrs} failure="boom"><failure type="testCodeFailure" message="boom &lt;${c.name}>">Error: boom</failure></testcase>`
      : `<testcase ${attrs}/>`;
  });
  return `<?xml version="1.0" encoding="utf-8"?>\n<testsuites>\n${body.join("\n")}\n</testsuites>\n`;
}

const cwd = "/repo";
const A = "/repo/test/a.test.ts";
const B = "/repo/test/b.test.ts";

/** A rerun command stub: records what it was asked to run and writes the given JUnit. */
function stubRerun(xml: string | null, exitCode: number) {
  const calls: string[][] = [];
  const spawn: SpawnCommand = async (argv) => {
    calls.push([...argv]);
    const junitArg = argv.find((arg) => arg.startsWith("--junit="));
    if (xml !== null && junitArg) writeFileSync(junitArg.slice("--junit=".length), xml);
    return exitCode;
  };
  return { calls, spawn };
}

let fixture = 0;
function writeFixture(xml: string): string {
  const path = join(scratch, `first-${fixture++}.xml`);
  writeFileSync(path, xml);
  return path;
}

function rerunOpts(junitPath: string, exitCode: number | null, spawn: SpawnCommand) {
  return {
    junitPath,
    exitCode,
    template: ["run-tests", "--junit={junit}", "{files}"],
    rerunJUnitPath: join(scratch, `rerun-${fixture++}.xml`),
    runner: "junit",
    job: "unit (node 24, shard 1/6)",
    cwd,
    spawn,
  };
}

describe("rerun mode", () => {
  test("a test that fails, then passes on the rerun of its file, is a flake", async () => {
    const first = writeFixture(junit([
      { name: "fails", file: A, failed: true, classname: "grp" },
      { name: "ok", file: A },
      { name: "other", file: B },
    ]));
    const stub = stubRerun(junit([{ name: "fails", file: A, classname: "grp" }, { name: "ok", file: A }]), 0);
    const result = await rerunJUnit(rerunOpts(first, 1, stub.spawn));
    // Only the failed file is rerun, through the shared template expansion.
    assert.equal(stub.calls.length, 1);
    assert.deepEqual(stub.calls[0]!.slice(0, 1), ["run-tests"]);
    assert.deepEqual(stub.calls[0]!.slice(2), ["test/a.test.ts"]);
    assert.deepEqual(result.failures, []);
    assert.deepEqual(result.errors, []);
    assert.equal(result.flakes.length, 1);
    const flake = result.flakes[0]!;
    assert.equal(flake.name, "grp > fails");
    assert.equal(flake.file, "test/a.test.ts");
    assert.equal(flake.job, "unit (node 24, shard 1/6)");
    assert.equal(flake.message, "boom <fails>");
    assert.equal(flake.key, flakeKey("junit", "test/a.test.ts", "grp > fails"));
  });

  test("a test that fails twice is a real failure", async () => {
    const first = writeFixture(junit([{ name: "fails", file: A, failed: true }]));
    const stub = stubRerun(junit([{ name: "fails", file: A, failed: true }]), 1);
    const result = await rerunJUnit(rerunOpts(first, 1, stub.spawn));
    assert.deepEqual(result.flakes, []);
    assert.equal(result.failures.length, 1);
    assert.equal(result.failures[0]!.name, "fails");
  });

  test("a test the rerun does not report is a real failure", async () => {
    const first = writeFixture(junit([{ name: "fails", file: A, failed: true }]));
    const stub = stubRerun(junit([{ name: "something else", file: A }]), 0);
    const result = await rerunJUnit(rerunOpts(first, 1, stub.spawn));
    assert.equal(result.failures.length, 1);
    assert.deepEqual(result.flakes, []);
  });

  test("a test that passed and then failed on the rerun is a flake too", async () => {
    const first = writeFixture(junit([{ name: "fails", file: A, failed: true }, { name: "was ok", file: A }]));
    const stub = stubRerun(junit([{ name: "fails", file: A }, { name: "was ok", file: A, failed: true }]), 1);
    const result = await rerunJUnit(rerunOpts(first, 1, stub.spawn));
    assert.deepEqual(result.flakes.map((f) => f.name).sort(), ["fails", "was ok"]);
    assert.deepEqual(result.failures, []);
    assert.deepEqual(result.errors, []);
  });

  test("all passing: nothing is rerun", async () => {
    const first = writeFixture(junit([{ name: "ok", file: A }]));
    const stub = stubRerun(null, 0);
    const result = await rerunJUnit(rerunOpts(first, 0, stub.spawn));
    assert.equal(stub.calls.length, 0);
    assert.deepEqual(result, { flakes: [], failures: [], errors: [] });
  });

  test("unreadable first results fail the job instead of guessing", async () => {
    const stub = stubRerun(null, 0);
    const missing = await rerunJUnit(rerunOpts(join(scratch, "nope.xml"), 1, stub.spawn));
    assert.equal(stub.calls.length, 0);
    assert.equal(missing.errors.length, 1);
    assert.match(missing.errors[0]!, /exited 1 and no JUnit results/);

    const broken = await rerunJUnit(rerunOpts(writeFixture("<testsuites><testcase"), 1, stub.spawn));
    assert.match(broken.errors[0]!, /not well-formed/);
  });

  test("a failed command with no failed test is an error, not a pass", async () => {
    const first = writeFixture(junit([{ name: "ok", file: A }]));
    const stub = stubRerun(null, 0);
    const result = await rerunJUnit(rerunOpts(first, 1, stub.spawn));
    assert.equal(stub.calls.length, 0);
    assert.match(result.errors[0]!, /exited 1, but no test in its JUnit results failed/);
  });

  test("unreadable rerun results make every first failure real", async () => {
    const first = writeFixture(junit([{ name: "fails", file: A, failed: true }]));
    const stub = stubRerun(null, 1);
    const result = await rerunJUnit(rerunOpts(first, 1, stub.spawn));
    assert.equal(result.failures.length, 1);
    assert.match(result.errors[0]!, /the rerun exited 1 and no JUnit results/);
  });

  test("a rerun that exits non-zero with every test passing is an error", async () => {
    const first = writeFixture(junit([{ name: "fails", file: A, failed: true }]));
    const stub = stubRerun(junit([{ name: "fails", file: A }]), 2);
    const result = await rerunJUnit(rerunOpts(first, 1, stub.spawn));
    assert.equal(result.flakes.length, 1);
    assert.match(result.errors[0]!, /the rerun exited 2/);
  });

  test("the committed bundle runs a real rerun and exits by the verdict", () => {
    // A fake runner: fails `flaky` unless FLAKE_RERUN is set, the way the CI proof's
    // deliberately flaky test is keyed on the rerun, and always fails `broken`.
    const work = join(scratch, "bundle");
    mkdirSync(join(work, "test"), { recursive: true });
    for (const file of ["a", "b"]) writeFileSync(join(work, "test", `${file}.test.ts`), "");
    const fake = join(work, "fake-runner.mjs");
    writeFileSync(fake, `
      import { writeFileSync } from "node:fs";
      const [junitPath, ...files] = process.argv.slice(2);
      const cases = files.map((f) => '<testcase name="flaky" classname="test" file="' + process.cwd() + '/' + f + '"/>');
      writeFileSync(junitPath, '<testsuites>' + cases.join('') + '</testsuites>');
    `);
    const first = join(work, "first.xml");
    writeFileSync(first, junit([
      { name: "flaky", file: join(work, "test/a.test.ts"), failed: true },
      { name: "fine", file: join(work, "test/b.test.ts") },
    ]));
    const reportPath = join(work, "out", "report.json");
    const summaryPath = join(work, "summary.md");
    const outputPath = join(work, "output.txt");
    const run = spawnSync(process.execPath, [join(actionDir, "index.mjs")], {
      cwd: work,
      encoding: "utf8",
      env: {
        PATH: process.env.PATH,
        RUNNER_TEMP: work,
        GITHUB_STEP_SUMMARY: summaryPath,
        GITHUB_OUTPUT: outputPath,
        GITHUB_REPOSITORY: "o/r",
        GITHUB_SHA: "deadbeef",
        GITHUB_REF_NAME: "main",
        GITHUB_RUN_ID: "42",
        INPUT_MODE: "rerun",
        INPUT_REPORT: reportPath,
        INPUT_JOB: "unit (node 24, shard 1/6)",
        INPUT_JUNIT: first,
        "INPUT_EXIT-CODE": "1",
        "INPUT_RERUN-COMMAND": `${process.execPath} ${fake} {junit} {files}`,
      },
    });
    assert.equal(run.status, 0, run.stdout + run.stderr);
    const report = JSON.parse(readFileSync(reportPath, "utf8")) as FlakeReport;
    assert.equal(report.commit, "deadbeef");
    assert.equal(report.runUrl, "https://github.com/o/r/actions/runs/42");
    assert.deepEqual(report.flakes.map((f) => [f.file, f.name]), [["test/a.test.ts", "flaky"]]);
    assert.match(readFileSync(summaryPath, "utf8"), /1 flaky test/);
    assert.match(readFileSync(outputPath, "utf8"), /flakes=1\nfailures=0/);
    assert.match(run.stdout, /::warning title=Flaky test::flaky \(test\/a\.test\.ts\)/);
  });
});

describe("Playwright retries", () => {
  const pwReport = {
    config: { rootDir: "/repo/e2e/specs" },
    suites: [{
      title: "board.spec.ts",
      file: "board.spec.ts",
      specs: [
        {
          title: "top-level flake",
          file: "board.spec.ts",
          tests: [{ status: "flaky", results: [{ error: { message: "\u001b[31mTimed out\u001b[39m" } }, {}] }],
        },
        { title: "passes", file: "board.spec.ts", tests: [{ status: "expected", results: [{}] }] },
      ],
      suites: [{
        title: "drag",
        file: "board.spec.ts",
        specs: [{
          title: "really broken",
          file: "board.spec.ts",
          tests: [{ status: "unexpected", results: [{ error: { message: "nope" } }, { error: { message: "nope" } }] }],
        }],
      }],
    }],
    errors: [{ message: "worker crashed" }],
  };

  test("flaky is a flake, unexpected a failure, global errors an error", () => {
    const result = classifyPlaywright(pwReport, { cwd: "/repo", job: "e2e (shard 1/15)" });
    assert.deepEqual(result.flakes.map((f) => [f.file, f.name, f.message, f.runner]), [
      ["e2e/specs/board.spec.ts", "top-level flake", "Timed out", "playwright"],
    ]);
    assert.deepEqual(result.failures.map((f) => f.name), ["drag > really broken"]);
    assert.equal(result.errors.length, 1);
    assert.match(result.errors[0]!, /e2e \(shard 1\/15\): Playwright reported an error outside any test: worker crashed/);
  });
});

// An in-memory GitHub for the few endpoints the action calls.
interface FakeIssue {
  number: number;
  html_url: string;
  title: string;
  state: "open" | "closed";
  body: string;
  created_at: string;
  labels: { name: string }[];
  comments: { body: string; created_at: string }[];
  events: { event: string; created_at: string }[];
}

function fakeGitHub(opts: { forbid?: RegExp; gone?: RegExp; now: Date }) {
  const labels = new Set<string>();
  const issues: FakeIssue[] = [];
  const checkRuns: Record<string, unknown>[] = [];
  const writes: string[] = [];
  // GitHub's clock: every write lands a millisecond after the one before it.
  let ticks = 0;
  const stamp = () => new Date(opts.now.getTime() + ++ticks).toISOString();
  const reply = (status: number, value: unknown = null) => ({
    status,
    ok: status < 300,
    text: async () => (value === null ? "" : JSON.stringify(value)),
  });
  const fetch: FetchLike = async (url, init) => {
    const { pathname, searchParams } = new URL(url);
    const path = pathname.replace(/^\/repos\/o\/r/, "");
    const body = init.body ? JSON.parse(init.body) : undefined;
    if (init.method !== "GET") {
      writes.push(`${init.method} ${path}`);
      if (opts.forbid?.test(`${init.method} ${path}`)) return reply(403, { message: "Resource not accessible by integration" });
      if (opts.gone?.test(`${init.method} ${path}`)) return reply(404, { message: "Not Found" });
    }
    const page = Number(searchParams.get("page") ?? "1");
    const paged = <T>(items: T[]) => reply(200, items.slice((page - 1) * 100, page * 100));
    let m: RegExpExecArray | null;
    if ((m = /^\/labels\/(.+)$/.exec(path)) && init.method === "GET") {
      return labels.has(decodeURIComponent(m[1]!)) ? reply(200, {}) : reply(404, {});
    }
    if (path === "/labels" && init.method === "POST") {
      labels.add(body.name);
      return reply(201, {});
    }
    if (path === "/issues" && init.method === "GET") {
      const label = searchParams.get("labels")!;
      return paged(issues.filter((i) => i.labels.some((l) => l.name === label)));
    }
    if (path === "/issues" && init.method === "POST") {
      const issue: FakeIssue = {
        number: issues.length + 1,
        html_url: `https://github.com/o/r/issues/${issues.length + 1}`,
        title: body.title,
        state: "open",
        body: body.body,
        created_at: stamp(),
        labels: body.labels.map((name: string) => ({ name })),
        comments: [],
        events: [],
      };
      issues.push(issue);
      return reply(201, issue);
    }
    if ((m = /^\/issues\/(\d+)(\/.*)?$/.exec(path))) {
      const issue = issues[Number(m[1]) - 1]!;
      const rest = m[2] ?? "";
      if (rest === "" && init.method === "PATCH") {
        if (body.state === "open" && issue.state === "closed") issue.events.push({ event: "reopened", created_at: stamp() });
        if (body.state) issue.state = body.state;
        if (body.body) issue.body = body.body;
        return reply(200, issue);
      }
      if (rest === "/comments" && init.method === "GET") return paged(issue.comments);
      if (rest === "/comments" && init.method === "POST") {
        issue.comments.push({ body: body.body, created_at: stamp() });
        return reply(201, {});
      }
      if (rest === "/events") return paged(issue.events);
      if (rest === "/labels" && init.method === "POST") {
        for (const name of body.labels) issue.labels.push({ name });
        return reply(200, []);
      }
      if ((m = /^\/labels\/(.+)$/.exec(rest)) && init.method === "DELETE") {
        const name = decodeURIComponent(m[1]!);
        if (!issue.labels.some((l) => l.name === name)) return reply(404, { message: "Label does not exist" });
        issue.labels = issue.labels.filter((l) => l.name !== name);
        return reply(200, []);
      }
    }
    if (path === "/check-runs" && init.method === "POST") {
      checkRuns.push(body);
      return reply(201, {});
    }
    return reply(500, { message: `unhandled ${init.method} ${path}` });
  };
  const client = gitHubClient({ apiUrl: "https://api.github.com", token: "t", fetch });
  const seedIssue = (issue: Partial<FakeIssue> & { key: string }) => {
    const number = issues.length + 1;
    issues.push({
      number,
      html_url: `https://github.com/o/r/issues/${number}`,
      title: "Flaky test: x",
      state: "open",
      body: `${flakeIssueMarker(issue.key)}\n<!-- mission-flake-count:v1 -->Occurrences counted: **1**\n\n${flakeOccurrenceMarker(new Date(issue.created_at ?? opts.now))}`,
      created_at: opts.now.toISOString(),
      labels: [{ name: "flaky-test" }],
      comments: [],
      events: [],
      ...issue,
    });
    return issues[number - 1]!;
  };
  return { client, labels, issues, checkRuns, writes, seedIssue };
}

const NOW = new Date("2026-09-28T12:00:00.000Z");
const daysAgo = (days: number) => new Date(NOW.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

const PR_EVENT = {
  pull_request: {
    number: 9,
    head: { sha: "headsha", ref: "feat/x", repo: { full_name: "o/r" } },
    base: { repo: { full_name: "o/r" } },
  },
};
const ENV = { GITHUB_REPOSITORY: "o/r", GITHUB_SHA: "mergesha", GITHUB_RUN_ID: "5", GITHUB_REF_NAME: "9/merge" };
const ctx: RunContext = runContextFrom(ENV, PR_EVENT);
/** A separate CI run of the same PR: the same run id is a replay of one run. */
const runCtx = (id: number): RunContext => runContextFrom({ ...ENV, GITHUB_RUN_ID: String(id) }, PR_EVENT);

function flake(name: string, job = "unit (node 24, shard 1/6)"): FlakeReportTest {
  return { key: flakeKey("junit", "test/a.test.ts", name), runner: "junit", file: "test/a.test.ts", name, message: "boom", job };
}

function jobReport(flakes: FlakeReportTest[], failures: FlakeReportTest[] = []) {
  const report: FlakeReport = {
    version: 1, commit: "headsha", ref: "feat/x", pullRequest: 9, runUrl: ctx.runUrl,
    flakes, failures, errors: [], issues: [],
  };
  return { source: `r${Math.random()}.json`, text: JSON.stringify(report) };
}

describe("publish mode", () => {
  test("the context uses the PR head commit, never the merge commit, and detects forks", () => {
    assert.equal(ctx.commit, "headsha");
    assert.equal(ctx.ref, "feat/x");
    assert.equal(ctx.pullRequest, 9);
    assert.equal(ctx.readOnlyReason, null);
    // Actions sets GITHUB_HEAD_REF to "" outside pull requests; the live proof caught "(no branch)".
    const push = runContextFrom({ ...ENV, GITHUB_HEAD_REF: "", GITHUB_REF_NAME: "main" }, { ref: "refs/heads/main" });
    assert.equal(push.commit, "mergesha");
    assert.equal(push.ref, "main");
    assert.equal(push.pullRequest, null);
    const fork = runContextFrom(ENV, {
      pull_request: { ...PR_EVENT.pull_request, head: { ...PR_EVENT.pull_request.head, repo: { full_name: "someone/r" } } },
    });
    assert.match(fork.readOnlyReason!, /fork/);
  });

  test("no flakes: a success check on the head commit, labels ensured, no issue", async () => {
    const gh = fakeGitHub({ now: NOW });
    const result = await publish({ ctx, reports: [jobReport([])], configText: null, client: gh.client, now: NOW });
    assert.equal(result.conclusion, "success");
    assert.equal(gh.checkRuns.length, 1);
    const run = gh.checkRuns[0] as { name: string; head_sha: string; conclusion: string; output: { title: string; summary: string } };
    assert.equal(run.name, FLAKY_TESTS_CHECK_NAME);
    assert.equal(run.head_sha, "headsha");
    assert.equal(run.conclusion, "success");
    assert.equal(run.output.title, "No flaky tests");
    assert.deepEqual(parseFlakeSummary(run.output.summary)?.flakes, []);
    assert.deepEqual([...gh.labels].sort(), ["flaky-test", "flaky-test:actionable"]);
    assert.equal(gh.issues.length, 0);
  });

  test("a new flake opens an issue and the neutral check links it", async () => {
    const gh = fakeGitHub({ now: NOW });
    const result = await publish({
      ctx,
      // The same test flaking in two jobs is one occurrence.
      reports: [jobReport([flake("fails")]), jobReport([flake("fails", "unit (node 26, shard 1/6)")], [flake("real")])],
      configText: readFileSync(join(root, ".mission", "testing.json"), "utf8"),
      client: gh.client,
      now: NOW,
    });
    assert.equal(result.conclusion, "neutral");
    assert.equal(gh.issues.length, 1);
    const issue = gh.issues[0]!;
    assert.equal(issue.title, "Flaky test: fails (test/a.test.ts)");
    assert.ok(issue.body.includes(flakeIssueMarker(flake("fails").key)));
    assert.ok(issue.body.includes(flakeOccurrenceMarker(NOW)));
    assert.match(issue.body, /pull request #9 \(`feat\/x`\) at `headsha`/);
    assert.match(issue.body, /unit \(node 24, shard 1\/6\), unit \(node 26, shard 1\/6\)/);
    assert.deepEqual(issue.labels.map((l) => l.name), ["flaky-test"]);
    const run = gh.checkRuns[0] as { conclusion: string; output: { title: string; summary: string } };
    assert.equal(run.conclusion, "neutral");
    assert.equal(run.output.title, "2 flaky tests");
    const parsed = parseFlakeSummary(run.output.summary)!;
    assert.equal(parsed.failures.length, 1);
    assert.deepEqual(parsed.issues, [{ key: flake("fails").key, number: 1, url: issue.html_url, occurrences: 1, actionable: false }]);
    assert.match(run.output.summary, /\[#1\]\(https:\/\/github\.com\/o\/r\/issues\/1\)/);
  });

  test("occurrences in the window reach the threshold and add the actionable label", async () => {
    const gh = fakeGitHub({ now: NOW });
    const issue = gh.seedIssue({
      key: flake("fails").key,
      created_at: daysAgo(40),
      comments: [
        { body: `${flakeOccurrenceMarker(new Date(daysAgo(35)))}\nold`, created_at: daysAgo(35) },
        { body: `${flakeOccurrenceMarker(new Date(daysAgo(10)))}\nrecent`, created_at: daysAgo(10) },
        { body: "a human comment", created_at: daysAgo(5) },
      ],
    });
    // The body's first occurrence and the 35-day-old one have left the 30-day window: 1 + now.
    let result = await publish({ ctx: runCtx(101), reports: [jobReport([flake("fails")])], configText: null, client: gh.client, now: NOW });
    assert.deepEqual(result.report.issues.map((i) => [i.occurrences, i.actionable]), [[2, false]]);
    assert.equal(issue.comments.length, 4);
    assert.match(issue.comments[3]!.body, /^<!-- mission-flake-occurrence:v1 at=2026-09-28T12:00:00\.000Z -->/);
    assert.match(issue.body, /Occurrences counted: \*\*2\*\* in the last 30 days/);
    assert.ok(!issue.labels.some((l) => l.name === "flaky-test:actionable"));

    result = await publish({ ctx: runCtx(102), reports: [jobReport([flake("fails")])], configText: null, client: gh.client, now: NOW });
    assert.deepEqual(result.report.issues.map((i) => [i.occurrences, i.actionable]), [[3, true]]);
    assert.ok(issue.labels.some((l) => l.name === "flaky-test:actionable"));
    assert.match(issue.body, /Occurrences counted: \*\*3\*\*/);
  });

  test("a closed issue is reopened, counted from the reopen, and loses the actionable label", async () => {
    const gh = fakeGitHub({ now: NOW });
    const issue = gh.seedIssue({
      key: flake("fails").key,
      state: "closed",
      labels: [{ name: "flaky-test" }, { name: "flaky-test:actionable" }],
      comments: [1, 2, 3].map((d) => ({ body: flakeOccurrenceMarker(new Date(daysAgo(d))), created_at: daysAgo(d) })),
    });
    const result = await publish({ ctx, reports: [jobReport([flake("fails")])], configText: null, client: gh.client, now: NOW });
    assert.equal(issue.state, "open");
    assert.deepEqual(result.report.issues.map((i) => [i.occurrences, i.actionable]), [[1, false]]);
    assert.deepEqual(issue.labels.map((l) => l.name), ["flaky-test"]);

    // The next occurrence counts only what came after the reopen.
    const later = new Date(NOW.getTime() + 60_000);
    const again = await publish({ ctx: runCtx(2), reports: [jobReport([flake("fails")])], configText: null, client: gh.client, now: later });
    assert.deepEqual(again.report.issues.map((i) => i.occurrences), [2]);
  });

  test("a closed issue that did not flake loses the actionable label", async () => {
    const gh = fakeGitHub({ now: NOW });
    const issue = gh.seedIssue({
      key: flake("fixed").key,
      state: "closed",
      labels: [{ name: "flaky-test" }, { name: "flaky-test:actionable" }],
    });
    await publish({ ctx, reports: [jobReport([])], configText: null, client: gh.client, now: NOW });
    assert.equal(issue.state, "closed");
    assert.deepEqual(issue.labels.map((l) => l.name), ["flaky-test"]);
  });

  test("two runs that open the same new flake at once converge on one issue", async () => {
    const gh = fakeGitHub({ now: NOW });
    const run = (id: number) => publish({ ctx: runCtx(id), reports: [jobReport([flake("fails")])], configText: null, client: gh.client, now: NOW });
    const [first, second] = await Promise.all([run(11), run(12)]);
    // Both created one (GitHub has no conditional create); the later one retired itself.
    assert.equal(gh.issues.length, 2);
    const withKey = gh.issues.filter((i) => i.body.includes(flakeIssueMarker(flake("fails").key)));
    assert.deepEqual(withKey.map((i) => [i.number, i.state]), [[1, "open"]]);
    const retired = gh.issues[1]!;
    assert.equal(retired.state, "closed");
    assert.ok(retired.body.includes("<!-- mission-flake-duplicate:v1 of=1 -->"));
    // The retired run's occurrence landed on the canonical issue, and both checks link it.
    assert.equal(gh.issues[0]!.comments.length, 1);
    assert.deepEqual([first, second].map((r) => r.report.issues[0]!.number), [1, 1]);
    assert.equal(second.report.issues[0]!.occurrences, 2);

    // Later runs find only the canonical issue.
    const later = await publish({ ctx: runCtx(13), reports: [jobReport([flake("fails")])], configText: null, client: gh.client, now: NOW });
    assert.deepEqual(later.report.issues.map((i) => [i.number, i.occurrences]), [[1, 3]]);
    assert.equal(retired.state, "closed");
  });

  test("two runs recording occurrences at once still cross the threshold", async () => {
    const gh = fakeGitHub({ now: NOW });
    const issue = gh.seedIssue({ key: flake("fails").key, created_at: daysAgo(1) });
    const run = (id: number) => publish({ ctx: runCtx(id), reports: [jobReport([flake("fails")])], configText: null, client: gh.client, now: NOW });
    const results = await Promise.all([run(21), run(22)]);
    // Body + two comments = 3: whichever run recounts after both posts adds the label.
    assert.equal(issue.comments.length, 2);
    assert.ok(results.some((r) => r.report.issues[0]!.actionable));
    assert.ok(issue.labels.some((l) => l.name === "flaky-test:actionable"));
  });

  test("two runs reopening the same issue at once both finish every flake", async () => {
    const gh = fakeGitHub({ now: NOW });
    const reopened = gh.seedIssue({
      key: flake("fails").key,
      state: "closed",
      labels: [{ name: "flaky-test" }, { name: "flaky-test:actionable" }],
    });
    const run = (id: number) => publish({
      ctx: runCtx(id),
      reports: [jobReport([flake("fails"), flake("other")])],
      configText: null,
      client: gh.client,
      now: NOW,
    });
    // Both see the stale actionable label and remove it; the second DELETE answers 404.
    const results = await Promise.all([run(31), run(32)]);
    for (const result of results) {
      assert.ok(!result.notes.some((note) => /cannot write issues/.test(note)), result.notes.join("\n"));
      // The flake after the reopened one is still recorded and linked.
      assert.deepEqual(result.report.issues.map((i) => i.key), [flake("fails").key, flake("other").key]);
    }
    assert.equal(gh.writes.filter((w) => w === "DELETE /issues/1/labels/flaky-test%3Aactionable").length, 2);
    assert.equal(reopened.state, "open");
    assert.deepEqual(reopened.labels.map((l) => l.name), ["flaky-test"]);
  });

  test("re-running the publish job for the same CI run records nothing twice", async () => {
    const gh = fakeGitHub({ now: NOW });
    const issue = gh.seedIssue({ key: flake("fails").key, created_at: daysAgo(1) });
    const replay = () => publish({ ctx: runCtx(41), reports: [jobReport([flake("fails"), flake("new")])], configText: null, client: gh.client, now: NOW });
    const first = await replay();
    const second = await replay();
    assert.equal(issue.comments.length, 1);
    assert.match(issue.comments[0]!.body, /<!-- mission-flake-run:v1 url=https:\/\/github\.com\/o\/r\/actions\/runs\/41 -->/);
    // The new flake's issue carries the run marker in its body, so it gains no comment either.
    const created = gh.issues.find((i) => i.body.includes(flakeIssueMarker(flake("new").key)))!;
    assert.equal(created.comments.length, 0);
    assert.equal(gh.issues.length, 2);
    assert.deepEqual(second.report.issues, first.report.issues);
  });

  // Each write in one flake's update, failing with a 404 the way it would if a concurrent hand
  // deleted, transferred or locked that issue mid-run.
  const goneCases = [
    { write: "reopening it", gone: /^PATCH \/issues\/1$/, state: "closed" as const, config: null },
    { write: "posting the occurrence", gone: /^POST \/issues\/1\/comments$/, state: "open" as const, config: null },
    { write: "adding the actionable label", gone: /^POST \/issues\/1\/labels$/, state: "open" as const, config: '{"flakes":{"actionableAfter":1}}' },
    { write: "refreshing the count", gone: /^PATCH \/issues\/1$/, state: "open" as const, config: null },
  ];
  for (const c of goneCases) {
    test(`a 404 while ${c.write} costs only that flake, not the run`, async () => {
      const gh = fakeGitHub({ now: NOW, gone: c.gone });
      gh.seedIssue({ key: flake("fails").key, state: c.state });
      const result = await publish({
        ctx,
        reports: [jobReport([flake("fails"), flake("other")])],
        configText: c.config,
        client: gh.client,
        now: NOW,
      });
      assert.ok(result.notes.some((note) => note.startsWith("Could not update the flake issue for fails (test/a.test.ts): GitHub")));
      assert.ok(!result.notes.some((note) => /cannot write issues/.test(note)), result.notes.join("\n"));
      // The next flake is still recorded and linked, and the check still publishes.
      assert.deepEqual(result.report.issues.map((i) => i.key), [flake("other").key]);
      assert.equal(gh.issues.filter((i) => i.body.includes(flakeIssueMarker(flake("other").key))).length, 1);
      assert.equal(gh.checkRuns.length, 1);
    });
  }

  test("a 403 still ends the issue pass as a missing permission", async () => {
    const gh = fakeGitHub({ now: NOW, forbid: /^POST \/issues\/1\/comments$/ });
    gh.seedIssue({ key: flake("fails").key });
    const result = await publish({ ctx, reports: [jobReport([flake("fails"), flake("other")])], configText: null, client: gh.client, now: NOW });
    assert.ok(result.notes.some((note) => /cannot write issues \(grant `issues: write`\)/.test(note)));
    assert.equal(gh.checkRuns.length, 1);
  });

  test("a fork PR writes nothing and says which writes it skipped", async () => {
    const gh = fakeGitHub({ now: NOW });
    const fork = { ...ctx, readOnlyReason: "this pull request comes from a fork, so its token is read-only" };
    const result = await publish({ ctx: fork, reports: [jobReport([flake("fails")])], configText: null, client: gh.client, now: NOW });
    assert.deepEqual(gh.writes, []);
    assert.equal(result.conclusion, "neutral");
    assert.ok(result.notes.some((note) => /Skipped updating flake issues and publishing the "Flaky tests" check: .*fork/.test(note)));
    assert.equal(parseFlakeSummary(result.summary)?.flakes.length, 1);
  });

  test("a token without issues: write still publishes the check", async () => {
    const gh = fakeGitHub({ now: NOW, forbid: /^POST \/labels/ });
    const result = await publish({ ctx, reports: [jobReport([flake("fails")])], configText: null, client: gh.client, now: NOW });
    assert.ok(result.notes.some((note) => /issues: write/.test(note)));
    assert.equal(gh.checkRuns.length, 1);
  });

  test("a token without checks: write is reported, not fatal", async () => {
    const gh = fakeGitHub({ now: NOW, forbid: /^POST \/check-runs/ });
    const result = await publish({ ctx, reports: [jobReport([])], configText: null, client: gh.client, now: NOW });
    assert.ok(result.notes.some((note) => /checks: write/.test(note)));
  });

  test("an unreadable per-job report is an error in the merged report", async () => {
    const gh = fakeGitHub({ now: NOW });
    const result = await publish({
      ctx,
      reports: [{ source: "bad.json", text: "{" }, { source: "old.json", text: '{"version":2}' }],
      configText: null,
      client: gh.client,
      now: NOW,
    });
    assert.deepEqual(result.report.errors, [
      "The report bad.json is not valid JSON.",
      "The report old.json is not a v1 flake report.",
    ]);
  });

  test("an invalid testing config skips issues but still publishes the check", async () => {
    const gh = fakeGitHub({ now: NOW });
    const result = await publish({ ctx, reports: [jobReport([flake("fails")])], configText: '{"flakes":{"lable":"x"}}', client: gh.client, now: NOW });
    assert.ok(result.notes.some((note) => /Skipped updating flake issues: .*testing\.json is not valid/.test(note)));
    assert.equal(gh.issues.length, 0);
    assert.equal(gh.checkRuns.length, 1);
  });
});
