#!/usr/bin/env node
// Regenerate `.github/actions/mission-flake-report/` from `src/flake-report-action/`.
//
//   npm run build:flake-report-action
//
// The action GitHub runs is a single bundled `index.mjs` plus its `action.yml`, both committed
// because a workflow can only use an action that is in the repository. This generator is the
// ONLY producer of those files: `test/flake-report-action.test.ts` imports `renderFlakeReportAction`
// and fails when the committed files differ from what it renders, so an edit to the source
// that was not regenerated, or a hand edit to the output, cannot merge.
//
// Run this after changing anything under `src/flake-report-action/` or the shared modules it
// bundles (`src/shared/flake-report.ts`, `junit.ts`, `testing-config.ts`,
// `command-template.ts`), and commit the result.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { FLAKE_REPORT_ACTION_VERSION } from "../src/flake-report-action/version.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const FLAKE_REPORT_ACTION_DIR = join(root, ".github", "actions", "mission-flake-report");

const HEADER = [
  `// mission-flake-report ${FLAKE_REPORT_ACTION_VERSION}`,
  "// Generated by scripts/build-flake-report-action.ts from src/flake-report-action/.",
  "// Do not edit: run `npm run build:flake-report-action` and commit the result.",
].join("\n");

const ACTION_YML = `# mission-flake-report ${FLAKE_REPORT_ACTION_VERSION}
# Generated by scripts/build-flake-report-action.ts. Do not edit: run
# \`npm run build:flake-report-action\` and commit the result. See docs/flaky-tests.md.
name: Mission Control flake report
description: Tell flaky tests from real failures, publish the "Flaky tests" check, and keep one GitHub issue per flaky test.

inputs:
  mode:
    description: "\`rerun\` in each test job, or \`publish\` in one job after all of them."
    required: true
  report:
    description: "rerun: where to write this job's report. publish: where to write the merged report (optional)."
    required: false
  job:
    description: "rerun: a label for this job, shown next to each test (for example \`unit (node 24, shard 3/6)\`)."
    required: false
  junit:
    description: "rerun: the first run's JUnit XML results."
    required: false
  exit-code:
    description: "rerun: the first run's exit code."
    required: false
  rerun-command:
    description: "rerun: the command that reruns failed files, split on whitespace; \`{files}\` becomes the files and \`{junit}\` the results path."
    required: false
  runner:
    description: "rerun: the runner name used in each test's key."
    required: false
    default: junit
  playwright-json:
    description: "rerun: read Playwright's JSON report (its own retries) instead of rerunning."
    required: false
  reports:
    description: "publish: a directory holding every job's report."
    required: false
  config:
    description: "publish: the committed testing settings, for the flake labels and threshold."
    required: false
    default: .mission/testing.json
  github-token:
    description: "publish: a token with \`checks: write\` and \`issues: write\`."
    required: false
    default: \${{ github.token }}

outputs:
  flakes:
    description: The number of flaky tests.
  failures:
    description: "rerun: the number of tests that failed twice."
  conclusion:
    description: "publish: the \\"Flaky tests\\" check's conclusion, \`success\` or \`neutral\`."

runs:
  using: node24
  main: index.mjs
`;

/** The generated files, by name, exactly as they are committed. */
export async function renderFlakeReportAction(): Promise<Record<string, string>> {
  const result = await build({
    absWorkingDir: root,
    entryPoints: ["src/flake-report-action/index.ts"],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node24",
    mainFields: ["module", "main"],
    alias: { "@shared": "./src/shared" },
    banner: { js: HEADER },
    legalComments: "none",
    charset: "utf8",
    write: false,
    logLevel: "silent",
  });
  const bundle = result.outputFiles[0];
  if (!bundle) throw new Error("esbuild produced no output");
  return { "index.mjs": bundle.text, "action.yml": ACTION_YML };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const files = await renderFlakeReportAction();
  mkdirSync(FLAKE_REPORT_ACTION_DIR, { recursive: true });
  for (const [name, text] of Object.entries(files)) writeFileSync(join(FLAKE_REPORT_ACTION_DIR, name), text);
  console.log(`Wrote ${Object.keys(files).join(", ")} to ${FLAKE_REPORT_ACTION_DIR}`);
}
