#!/usr/bin/env node

/**
 * Which test files one CI shard runs: `node scripts/unit-shard.mjs <index>/<total> [<suite>]`
 * prints them, one per line. The suite is `unit` when omitted; see `SHARD_SUITES`.
 *
 * Shards are balanced by recorded duration rather than by file index. Each file is weighted by
 * its milliseconds in the suite's timings file (generated by `npm run test:timings`, never
 * hand-edited); a file the timings do not name weighs the median of the ones they do, or the
 * same as every other file when they name none. Files are then dealt longest first, ties broken
 * by path, each to the lightest shard so far, lowest index on a tie.
 *
 * The timings only steer balance. The file set always comes from the glob, so a stale, partial
 * or empty timings file can make shards uneven, but never drops a test file or runs one twice.
 * `test/unit-shard.test.ts` holds that invariant.
 */

import { globSync, readFileSync } from "node:fs";
import { join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

/** The unit suite. `package.json`'s `test` script names the same glob. */
export const UNIT_TEST_GLOB = "test/**/*.test.ts";
export const SHARD_TIMINGS_PATH = "test/shard-timings.json";

/**
 * Each sharded suite: its files are `glob` under `dir`, listed relative to `dir`, and weighted by
 * `timings`. Linux unit shards use `unit`. Windows runners take several times as long, and not
 * uniformly, so the Windows jobs keep their own timings. A `windows-e2e` file list is relative to
 * Playwright's test directory, which is the form its `--test-list` takes.
 */
export const SHARD_SUITES = {
  unit: { dir: ".", glob: UNIT_TEST_GLOB, timings: SHARD_TIMINGS_PATH },
  "windows-unit": { dir: ".", glob: UNIT_TEST_GLOB, timings: "test/shard-timings-windows.json" },
  "windows-e2e": { dir: "e2e/specs", glob: "**/*.spec.ts", timings: "e2e/shard-timings-windows.json" },
};

function shardSuite(name) {
  if (!Object.hasOwn(SHARD_SUITES, name)) {
    throw new Error(`unknown suite ${JSON.stringify(name)}; expected one of ${Object.keys(SHARD_SUITES).join(", ")}`);
  }
  return SHARD_SUITES[name];
}

/** Every file of `suite` under `root`, as sorted POSIX paths relative to the suite's `dir`. */
export function suiteFiles(root, suite = "unit") {
  const { dir, glob } = shardSuite(suite);
  return globSync(glob, { cwd: join(root, dir) })
    .map((file) => file.split(sep).join("/"))
    .sort(comparePaths);
}

/** Every unit test file under `root`, as sorted repository-relative POSIX paths. */
export function unitTestFiles(root) {
  return suiteFiles(root, "unit");
}

/** The recorded timings of `suite` at `root`, or none when the file is absent. */
export function readShardTimings(root, suite = "unit") {
  const { timings } = shardSuite(suite);
  let text;
  try {
    text = readFileSync(join(root, timings), "utf8");
  } catch (err) {
    if (err?.code === "ENOENT") return {};
    throw err;
  }
  const parsed = JSON.parse(text);
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`${timings} must be an object mapping test files to milliseconds`);
  }
  return parsed;
}

function comparePaths(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function recordedMs(timings, file) {
  if (!Object.hasOwn(timings, file)) return null;
  const ms = timings[file];
  return typeof ms === "number" && Number.isFinite(ms) && ms >= 0 ? ms : null;
}

function median(values) {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = sorted.length >> 1;
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

/** Each file's weight: its recorded milliseconds, or the median of the recorded ones. */
export function shardWeights(files, timings) {
  const recorded = files.map((file) => recordedMs(timings, file)).filter((ms) => ms !== null);
  const fallback = recorded.length ? median(recorded) : 1;
  return new Map(files.map((file) => [file, recordedMs(timings, file) ?? fallback]));
}

/** Split `files` into `total` shards, longest first onto the lightest shard. */
export function partitionUnitTests(files, timings, total) {
  if (!Number.isInteger(total) || total < 1) throw new Error(`shard total must be a positive integer, got ${total}`);
  const unique = [...new Set(files)];
  const weights = shardWeights(unique, timings);
  const order = unique.sort((a, b) => weights.get(b) - weights.get(a) || comparePaths(a, b));
  const shards = Array.from({ length: total }, () => ({ files: [], ms: 0 }));
  for (const file of order) {
    let lightest = shards[0];
    for (const shard of shards) if (shard.ms < lightest.ms) lightest = shard;
    lightest.files.push(file);
    lightest.ms += weights.get(file);
  }
  return shards.map((shard) => shard.files);
}

/** Parse `<index>/<total>`, one-based. */
export function parseShardSpec(spec) {
  const match = /^(\d+)\/(\d+)$/.exec(spec ?? "");
  const index = Number(match?.[1]);
  const total = Number(match?.[2]);
  if (!match || total < 1 || index < 1 || index > total) {
    throw new Error(`expected <index>/<total> with 1 <= index <= total, got ${JSON.stringify(spec)}`);
  }
  return { index, total };
}

function main() {
  const root = join(fileURLToPath(import.meta.url), "..", "..");
  const { index, total } = parseShardSpec(process.argv[2]);
  const suite = process.argv[3] ?? "unit";
  const files = partitionUnitTests(suiteFiles(root, suite), readShardTimings(root, suite), total)[index - 1];
  // Handing `node --test` no files makes it discover its own default set, never this shard's.
  if (!files.length) throw new Error(`shard ${index}/${total} has no test files`);
  process.stdout.write(`${files.join("\n")}\n`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (err) {
    console.error(`unit-shard: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  }
}
